services:
  postgres:
    image: postgres:14.4-alpine3.16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: syncbase
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.0.4-alpine3.16
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
