name: Create diagram

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  project_structure:
    name: Project Structure
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
