name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    name: Lint commit message
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4

  lintcode:
    name: Lint source code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run stylelint
        run: yarn stylelint '**/*.css'
      - name: Run prettier
        run: yarn prettier --check '**/*.{json,md,yml}'
      - name: Run eslint
        run: yarn eslint . --max-warnings 0
      - name: Run typescript server checks
        run: yarn workspace @syncbase/server check-types
      - name: Run typescript web checks
        run: yarn workspace @syncbase/web check-types
