name: Lint

on: [push, pull_request]

jobs:
  commitlint:
    name: Commit message linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4

  lintcode:
    name: Source code linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run stylelint
        run: yarn stylelint "**/*.css"
      - name: Run prettier
        run: yarn prettier --check "**/*.{json,md,yml}"
      - name: Run eslint
        run: yarn eslint . --ext .js,.ts,.tsx --ignore-pattern "node_modules/.*" --max-warnings 0
      - name: Run typescript server checks
        run: yarn check-types:server
      - name: Run typescript web checks
        run: yarn check-types:web
