name: Lint

on: [push, pull_request]

jobs:
  commitlint:
    name: Commit message linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4

  lintcode:
    name: Source code linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run stylelint
        run: yarn stylelint '**/*.css'
      - name: Run prettier
        run: yarn prettier --check '**/*.{json,md,yml}'
      - name: Run eslint
        run: yarn eslint . --max-warnings 0
      - name: Run typescript server checks
        run: yarn workspace @syncbase/server check-types
      - name: Run typescript web checks
        run: yarn workspace @syncbase/web check-types
      - name: Run GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: "main:packages/server/schema.graphql"
          fail-on-breaking: true
          annotations: true
