name: UI Tests

on:
  push:
    branches:
      - main
    paths:
      - "packages/web/src/components/ui/**/*.tsx"

jobs:
  chromatic:
    name: Visual and composition
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build Storybook
        run: yarn workspace @syncbase/web build-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: 64e3a9911647
          workingDir: packages/web
